### PR TITLE
PLAT-7577 preview appetize platforms/versions

### PR DESCRIPTION
**Pull request by sgmagar**
## Ticket

[PLAT-7577](https://crowdbotics.atlassian.net/browse/PLAT-7577)
_Related tickets:_
_Related PRs:_

## Type of PR

- [ ] Bugfix
- [x] New feature
- [ ] Minor changes

## Changes introduced
Activate ios appetize builds
Update fastfile to generate new appetize app versions with each builds
Send Platform id and build versions as appetize metada webhook

## Test and review
Should be able to view historic appetize versions on dashboard

### CODE REVIEW

**Comment by mabdullahabid** [comment]
@sgmagar if I understand correctly, this implementation only shows the latest build of the Appetize so whether its iOS or Android, only the latest one is present in the link? How are we going to switch between iOS and Android previews on the frontend?

**Comment by mabdullahabid** [comment]
Should we store the links for both previews so that they are available at all times? Or would that be under a different ticket?

**Comment by sgmagar** [comment]
> Should we store the links for both previews separately so that they are available at all times? Or would that be under a different ticket?

On every build, it creates new app version on appetize. And we store all those appetize version on the platform metadata. If you look at the backend ticket for this, it's storing there.

**Review by mabdullahabid — APPROVED** [review]

**Comment by driverdan** [comment]
@sgmagar Abdullah approved this but you dismissed his review. Should he review again?

**Comment by sgmagar** [comment]
> @sgmagar Abdullah approved this but you dismissed his review. Should he review again?

I didn't dismiss it, not intentionally. may be i clicked somewhere. It's approved.

**Review by driverdan — APPROVED** [review]

**Pull request merged**
