### PR TITLE
PR for FAQ Module

### PR DESCRIPTION
**Pull request by tarun-crowdbotics**
## Ticket

PLAT-XXXX
_Related tickets:_
_Related PRs:_

## Type of PR
- [ ] New feature

## Changes introduced
- FAQ module

## Test and review
- Just add the module in your project
- For more info, please visit the README.md

_Describe how a reviewer should test your PR_
- Deploy the back-end code.
- add module in the project using yarn run add FAQ
- update the url from option/options.js
- then run the application

### CODE REVIEW

**Review by sumermpatel — APPROVED** [review]

**Review by sumermpatel — APPROVED** [review]
Front end react native code is good to go.

**Review by nilaysaxena — DISMISSED** [review]

**Review by saad-abid-crowdbotics — CHANGES_REQUESTED** [review]
1. Don't push .DS_Store file
2. Don't push the dist folder
3. Add preview file

**Comment by tarun-crowdbotics** [comment]
> 1. Don't push .DS_Store file
> 
>     2. Don't push the dist folder
> 
>     3. Add preview file

- Added Preview file.

**Comment by danielsousaio** [comment]
Superseded by #533

**Pull request closed without merging**
