### PR TITLE
PLAT-7404 Separating iOS and Android CircleCI config files

### PR DESCRIPTION
**Pull request by mabdullahabid**
## Ticket

PLAT-7404
_Related tickets:_
_Related PRs:_ https://github.com/crowdbotics/crowdbotics-slack-app/pull/3636

## Type of PR

- [ ] Bugfix
- [ ] New feature
- [x] Minor changes

## Changes introduced

This PR separates the CircleCI config files for mobile builds of iOS and Android.

Note: This must be released together with https://github.com/crowdbotics/crowdbotics-slack-app/pull/3636 in order to get the updated build_types during the build and deploy phase

## Test and review

Read Test and review for https://github.com/crowdbotics/crowdbotics-slack-app/pull/3636

### CODE REVIEW

**Review by danielsousaio — APPROVED** [review]

**Comment by mabdullahabid** [comment]
@danielsousaio please re-review

**Review by math-a3k — DISMISSED** [review]
Looks good to me :+1:

**Comment by mabdullahabid** [comment]
@danielsousaio @driverdan ready to merge

**Review by danielsousaio — APPROVED** [review]
Looks good

**Pull request merged**
