### PR TITLE
Android deployment sprint 23

### PR DESCRIPTION
**Pull request by leandrobono**
## Type of PR

- [ ] Bugfix
- [X] New feature
- [ ] Minor changes

## Changes introduced

_Describe the changes being introduced in this PR_
_Include screenshots if necessary_
_Please link any documentation reference that relate to the changes_

## Test and review

_Describe how a reviewer should test your PR_

### CODE REVIEW

**Review by mabdullahabid — DISMISSED** [review]

**Review by alaisgomes — COMMENTED** [review]
Noty sure if related to this PR changes, but running a fastlane build is failing out of the box. Does it mean it requires manual setup for a deployment to happen now? 
Getting this error
```

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:validateSigningRelease'.
> Keystore file '/home/aline/crowdbotics/modules/demo/android/app/my-upload-key.keystore' not found for signing config 'release'.
```

Tested executed simply by creating a demo app and bulding it:
```
yarn run demo
cd demo
bundle install
cd android
bundle exec fastlane deploy_appetize
```

If there's some intermediate step done by the backend or something, or a way to inject this key, please document it in the readme, or at the very least add the ticket number to this PR with some description to the introduced changes, so we can trace them in the future

**Review by danielsousaio — CHANGES_REQUESTED** [review]
Running `yarn run template` produces changes, which means that some files changes were not included as custom files to be overridden in the base template:
```
crowdbotics@modules $ yarn run template
yarn run v1.22.10
$ node scripts/template.js
Done in 0.10s.
crowdbotics@modules $ git diff
diff --git a/scaffold/template/android/app/build.gradle b/scaffold/template/android/app/build.gradle
index df6dd1aa..f75c1609 100644
--- a/scaffold/template/android/app/build.gradle
+++ b/scaffold/template/android/app/build.gradle
@@ -152,12 +152,6 @@ android {
             keyAlias 'androiddebugkey'
             keyPassword 'android'
         }
-        release {
-            storeFile file('my-upload-key.keystore')
-            storePassword 'my-key'
-            keyAlias 'my-key-alias'
-            keyPassword 'my-key'
-        }
     }
     buildTypes {
         debug {
@@ -166,7 +160,7 @@ android {
         release {
             // Caution! In production, you need to generate your own keystore file.
             // see https://reactnative.dev/docs/signed-apk-android.
-            signingConfig signingConfigs.release
+            signingConfig signingConfigs.debug
             minifyEnabled enableProguardInReleaseBuilds
             proguardFiles getDefaultProguardFile("proguard-android.txt"), "proguard-rules.pro"
         }
diff --git a/scaffold/template/android/build.gradle b/scaffold/template/android/build.gradle
index ac4d6471..93232f5f 100644
--- a/scaffold/template/android/build.gradle
+++ b/scaffold/template/android/build.gradle
@@ -4,8 +4,8 @@ buildscript {
     ext {
         buildToolsVersion = "29.0.3"
         minSdkVersion = 21
-        compileSdkVersion = 30
-        targetSdkVersion = 30
+        compileSdkVersion = 29
+        targetSdkVersion = 29
         ndkVersion = "20.1.5948944"
     }
     repositories {
```

Could you please add those two `build.gradle` files as new files in the `scaffold/template/custom/android` and `scaffold/template/custom/android/app` directories?

Then make sure they are covered by the `scripts/install.js` copy logic.

**Review by GaboGomezT — DISMISSED** [review]

**Review by danielsousaio — CHANGES_REQUESTED** [review]
Same issue with `yarn run bootstrap`, custom files changes were not included in the scaffold:
```diff
diff --git a/dist/cookie/cookiecutter.json b/dist/cookie/cookiecutter.json
index 73d7bf85..166e783b 100644
--- a/dist/cookie/cookiecutter.json
+++ b/dist/cookie/cookiecutter.json
@@ -1,5 +1,5 @@
 {
-  "project_name": "{{cookiecutter.project_name}}",
+  "project_name": "",
   "project_slug": "{{cookiecutter.project_name|lower|replace(' ', '')|replace('-', '_')}}",
   "project_dash_slug": "{{cookiecutter.project_slug|replace('_', '-')}}",
   "project_description": "",
   
diff --git a/dist/cookie/{{cookiecutter.project_slug}}/android/app/src/main/AndroidManifest.xml b/dist/cookie/{{cookiecutter.project_slug}}/android/app/src/main/AndroidManifest.xml
index 49b62424..f4de2af9 100644
--- a/dist/cookie/{{cookiecutter.project_slug}}/android/app/src/main/AndroidManifest.xml
+++ b/dist/cookie/{{cookiecutter.project_slug}}/android/app/src/main/AndroidManifest.xml
@@ -5,14 +5,14 @@
 
     <application
       android:name=".MainApplication"
-      android:label="@string/original_app_name"
+      android:label="@string/app_name"
       android:icon="@mipmap/ic_launcher"
       android:roundIcon="@mipmap/ic_launcher_round"
       android:allowBackup="false"
       android:theme="@style/AppTheme">
       <activity
         android:name=".MainActivity"
-        android:label="@string/original_app_name"
+        android:label="@string/app_name"
         android:configChanges="keyboard|keyboardHidden|orientation|screenSize|uiMode"
         android:launchMode="singleTask"
         android:windowSoftInputMode="adjustResize"
         
diff --git a/dist/cookie/{{cookiecutter.project_slug}}/android/app/src/main/res/values/strings.xml b/dist/cookie/{{cookiecutter.project_slug}}/android/app/src/main/res/values/strings.xml
index 6d7f32ba..5d48510c 100644
--- a/dist/cookie/{{cookiecutter.project_slug}}/android/app/src/main/res/values/strings.xml
+++ b/dist/cookie/{{cookiecutter.project_slug}}/android/app/src/main/res/values/strings.xml
@@ -1,4 +1,3 @@
 <resources>
     <string name="app_name">{{cookiecutter.project_dash_slug}}</string>
-    <string name="original_app_name">{{cookiecutter.project_name}}</string>
 </resources>
```

**Review by danielsousaio — APPROVED** [review]

**Comment by mabdullahabid** [comment]
> Noty sure if related to this PR changes, but running a fastlane build is failing out of the box. Does it mean it requires manual setup for a deployment to happen now? Getting this error
> 
> ```
> 
> FAILURE: Build failed with an exception.
> 
> * What went wrong:
> Execution failed for task ':app:validateSigningRelease'.
> > Keystore file '/home/aline/crowdbotics/modules/demo/android/app/my-upload-key.keystore' not found for signing config 'release'.
> ```
> 
> Tested executed simply by creating a demo app and bulding it:
> 
> ```
> yarn run demo
> cd demo
> bundle install
> cd android
> bundle exec fastlane deploy_appetize
> ```
> 
> If there's some intermediate step done by the backend or something, or a way to inject this key, please document it in the readme, or at the very least add the ticket number to this PR with some description to the introduced changes, so we can trace them in the future

@alaisgomes as far as I can tell, those keys and the additional google play console keys are automatically generated and handled by the fastlane when a deployment is triggered from CB Dash. If it does mess with manual fastlane actions locally, then you are right, we need to add that to the README or docs somewhere.

I'm going to tag @leandrobono here so he can handle that once he's back on Monday. He has more experience with the specific steps we need to do so I'm going to merge this for now as its been approved and works on review apps.

**Pull request merged**
