### PR TITLE
PI-298: Package upgrades

### PR DESCRIPTION
**Pull request by Hesbon5600**
## Ticket

[PI-298](https://crowdbotics.atlassian.net/browse/PI-298)

Upgrade:
- `elliptic: 6.5.7`
- `ip: 1.1.9`
- `activesupport: 7.0.7.1`

_Related tickets:_
_Related PRs:_

## Type of PR

- [ ] Bugfix
- [ ] New feature
- [ ] Minor changes

Did you make changes to modules or created a new module?

- [ ] Yes, and have read the [modules updates checklist](https://github.com/crowdbotics/modules/#modules-updates-checklist) documentation and followed the instructions.
- [ ] No.

## Changes introduced

_Describe the changes being introduced in this PR_
_Include screenshots if necessary_
_Please link any documentation reference that relate to the changes_

## Test and review

_Describe how a reviewer should test your PR_

[PI-298]: https://crowdbotics.atlassian.net/browse/PI-298?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by driverdan** [comment]
Looks like the android and ios tests are failing. Could you take a look to see if they're a quick fix? For iOS it seems it's an old image that's no longer supported.

**Comment by Hesbon5600** [comment]
They are failing for all PRs. I can’t see any errors at a glance. Let me
see if I can resolve them

**Comment by Hesbon5600** [comment]
@driverdan We can merge this after @mabdullahabid has pushed a fix for the failing workflows

**Review by cruz636 — APPROVED** [review]
LGTM & tests are passing 👍🏾

**Review by mabdullahabid — DISMISSED** [review]

**Comment by Hesbon5600** [comment]
@driverdan Please merge this PR

**Review by driverdan — APPROVED** [review]

**Pull request merged**
