### PR TITLE
PLAT-11568: csrf_token configuration

### PR DESCRIPTION
**Pull request by alaisgomes**
## Ticket

PLAT-11568
_Related tickets:_
_Related PRs:_

## Type of PR

- [ ] Bugfix
- [x] New feature
- [ ] Minor changes

## Review checklist for scaffold changes

- [x] I have made no scaffold changes - ignore this section questions in that case
- [x] `yarn run template` produces no changes
- [x] `yarn run raw && yarn run cookie` produces no changes, except for `yarn.lock`
- [x] `yarn run demo` finishes successfully, `demo` directory gets created locally
- [x] **"Running the demo"** opens the app correctly in the welcome screen

## Changes introduced
Introducing csrf_token to the main django template html. Also added axios csrf token names for mobile builds.

## Test and review
This is hard to test with the local demo app, but I made the same changes to an app created with the scaffold and the CSRF token issues are gone from web login: https://crowdbotics-slack-dev.crowdbotics.com/dashboard/app/88809
The android requests also function as usual (csrf configuration is only available in web app)

### CODE REVIEW

**Review by danielsousaio — DISMISSED** [review]

**Comment by danielsousaio** [comment]
@alaisgomes `/dist/raw` has been added to `.gitignore` in the meanwhile, you can remove those files from the set of changes here. Looks good otherwise.

https://github.com/crowdbotics/modules/blob/2a211186280210a9dabb104ce9ed021dacec0da7/.gitignore#L207

**Comment by alaisgomes** [comment]
> @alaisgomes `/dist/raw` has been added to `.gitignore` in the meanwhile, you can remove those files from the set of changes here. Looks good otherwise.
> 
> https://github.com/crowdbotics/modules/blob/2a211186280210a9dabb104ce9ed021dacec0da7/.gitignore#L207

Fixed it!
Do you know why the CircleCI pipeline no longer works? Are we moving the modules stuff to GitHub actions or something?

**Comment by danielsousaio** [comment]
> Do you know why the CircleCI pipeline no longer works? Are we moving the modules stuff to GitHub actions or something?

The CircleCI pipeline is a work in progress for doing android/iOS builds.

**Comment by alaisgomes** [comment]
> The CircleCI pipeline is a work in progress for doing android/iOS builds.

Oh ok cool!

**Pull request merged**
