### PR TITLE
Phone Number Picker Module

### PR DESCRIPTION
**Pull request by cbshoaib**
## Type of PR

- [ ] Bugfix
- [x] New feature
- [ ] Minor changes

## Running the demo

In order to run the included demo app, run `yarn run bootstrap` and then `cd demo` and run both `npx react-native run-android` and `npx react-native start` in parallel.

## Review checklist for new or updated modules

Please go through the following checks:

- [x] I have included a `meta.json` file in the module's root directory
- [x] I have included a `preview.png` image in the module's root directory

React Native modules specific checks:

- [x] `yarn run demo` and `yarn run add app-menu <your-module>` runs correctly
- [x] **"Running the demo"** app shows the App Menu screen with an entry for your module
- [x] Clicking your module entry in the menu loads your module's initial screen correctly

## Changes introduced
Phone Number Picker Module Integration

## Test and review

1. Pick country code properly
Screenshot from 2023-02-24 20-14-02
Screenshot from 2023-02-24 20-23-50

### CODE REVIEW

**Review by danielsousaio — COMMENTED** [review]
Needs updated README.md

**Review by saad-abid-crowdbotics — DISMISSED** [review]
LGTM

**Review by danielsousaio — CHANGES_REQUESTED** [review]
This could become a `screen` module since it has no dependencies.

**Comment by cbshoaib** [comment]
> This could become a `screen` module since it has no dependencies.

Done.

**Comment by saad-abid-crowdbotics** [comment]
> This could become a `screen` module since it has no dependencies.

Done.

**Review by danielsousaio — APPROVED** [review]

**Pull request merged**
