### PR TITLE
PLAT-10336:  Change hardcoded email address in Fastfile

### PR DESCRIPTION
**Pull request by Hesbon5600**
## Ticket

[PLAT-10336](https://crowdbotics.atlassian.net/browse/PLAT-10336)

_Related PRs:_
[crowdbotics-slack-app - 4234](https://github.com/crowdbotics/crowdbotics-slack-app/pull/4234)

## Type of PR

- [x] Bugfix
- [ ] New feature
- [ ] Minor changes

## Running the demo

In order to run the included demo app, run `yarn run bootstrap` and then `cd demo` and run both `npx react-native run-android` and `npx react-native start` in parallel.

## Review checklist for new or updated modules

Please go through the following checks:

- [ ] I have made no modules changes - ignore this section questions in that case
- [ ] I have included a `meta.json` file in the module's root directory
- [ ] I have included a `preview.png` image in the module's root directory
- [ ] `yarn run parse` checks pass
- [ ] I updated the modules build (`/dist` directory) with `yarn run dist`

React Native modules specific checks:

- [ ] `yarn run demo` and `yarn run add app-menu <your-module>` runs correctly
- [ ] **"Running the demo"** app shows the App Menu screen with an entry for your module
- [ ] Clicking your module entry in the menu loads your module's initial screen correctly

Django modules specific checks:

- [ ] `python manage.py show_urls` shows that the module's urls are resolved correctly
- [ ] I have checked that the migrations are detected and run correctly
- [ ] I have checked that the admin is working correctly for the module

If your module is a "supermodule" and therefore contains both React Native and Django code, then please go through all of the checks above.

## Review checklist for scaffold changes

- [ ] I have made no scaffold changes - ignore this section questions in that case
- [ ] `yarn run template` produces no changes
- [ ] `yarn run raw && yarn run cookie` produces no changes, except for `yarn.lock`
- [ ] `yarn run demo` finishes successfully, `demo` directory gets created locally
- [ ] **"Running the demo"** opens the app correctly in the welcome screen

## Changes introduced

IOS Fastfile will now get the project owner email from CircleCi env variables

## Test and review

_Describe how a reviewer should test your PR_

1. Go to the review App and deploy an IOS app to testflight. 
2. The deployment should be successful

### CODE REVIEW

**Comment by sgmagar** [comment]
@Hesbon5600 To update modules, you should follow this:

1. Update inside `scaffold/template/custom`
2. Run `yarn run bootstrap`
Those inside raw and cookie are updated by this command.

Also, i see that .DS_Store file, you should remove that from git

**Comment by Hesbon5600** [comment]
> @Hesbon5600 To update modules, you should follow this:
> 
> 1. Update inside `scaffold/template/custom`
> 2. Run `yarn run bootstrap`
>    Those inside raw and cookie are updated by this command.
> 
> Also, i see that .DS_Store file, you should remove that from git

- I've run the command to update the `cookie` Fastfile
- I deleted the existing `.DS_Store` files and added it to `.gitignore` since they're autogenerated by VS Cod. Do we need to have them in the project?

**Review by sgmagar — DISMISSED** [review]
Looks good

**Review by sgmagar — APPROVED** [review]
Approving it. Can you set up the test pr on crowdbotics-slack-app, to test this in review app.

**Comment by Hesbon5600** [comment]
> Approving it. Can you set up the test pr on crowdbotics-slack-app, to test this in review app.

How do I do that without a PR on the slack-app repo?

**Comment by sgmagar** [comment]
> > Approving it. Can you set up the test pr on crowdbotics-slack-app, to test this in review app.
> 
> How do I do that without a PR on the slack-app repo branch?

You can create a test PR. With some dummy text

**Pull request merged**
